# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 763187c22c9bceb28aac45354a0933d7e26e2c70205fec918bb1e29e94050a895c2924e4223a1ec6c0c9db531845b3bd141363b9670f579fef971bad9ee4bf22

test:
  secret_key_base: a4e5d101af6377e5b99f439e842b59adacf6d41f1b05778fce17e553a40fef6d3a8a8705ce5bee77710c3bbf08c215de69f5e8c521a940c91069e981290e377e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
